/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversorCaF;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author damt207/
 */
public class JFrameConversor extends javax.swing.JFrame {

    /**
     * Creates new form JFrameConversor
     */
    public JFrameConversor() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_convertir = new javax.swing.JButton();
        jLabel2_Celsius = new javax.swing.JLabel();
        jTextField_ValorCelcius = new javax.swing.JTextField();
        jTextField_Respuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor C a F");
        setMaximumSize(new java.awt.Dimension(230, 200));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jButton_convertir.setBackground(new java.awt.Color(102, 255, 0));
        jButton_convertir.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton_convertir.setText("Convertir");
        jButton_convertir.setMaximumSize(new java.awt.Dimension(82, 22));
        jButton_convertir.setMinimumSize(new java.awt.Dimension(82, 22));
        jButton_convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_convertirActionPerformed(evt);
            }
        });

        jLabel2_Celsius.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2_Celsius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_Celsius.setText("Conversor");
        jLabel2_Celsius.setToolTipText("");

        jTextField_ValorCelcius.setToolTipText("");
        jTextField_ValorCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ValorCelciusActionPerformed(evt);
            }
        });
        jTextField_ValorCelcius.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_ValorCelciusKeyPressed(evt);
            }
        });

        jTextField_Respuesta.setToolTipText("");
        jTextField_Respuesta.setFocusable(false);

        jLabel1.setText("ºC");

        jLabel2.setText("ºF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2_Celsius, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextField_Respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jButton_convertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_ValorCelcius))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2_Celsius, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ValorCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton_convertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_convertirActionPerformed
        // TODO add your handling code here:
        ejecutar();
    }//GEN-LAST:event_jButton_convertirActionPerformed

    private void ejecutar() {
        String valorCelsius = jTextField_ValorCelcius.getText();
        double celsius;

        try {

            celsius = Double.parseDouble(valorCelsius);

            double fahren;

            fahren = (celsius * 9 / 5) + 32;

            jTextField_Respuesta.setForeground(Color.black);
            jTextField_Respuesta.setText(fahren + "");

        } catch (NumberFormatException e) {
            //System.err.println("Error Number Format Exception");

            jTextField_Respuesta.setForeground(Color.red);
            jTextField_Respuesta.setText("Error");

            if (e.getMessage().contains(",")) {
                panelComa();
            } else if (e.getMessage().contains("empty")) {
                panelInsertarValor();
            } else {
                panelLetra();
            }

        }

        jTextField_ValorCelcius.requestFocus();

    }

    private void panelInsertarValor() {
        JOptionPane jop = new JOptionPane("Introduce un dato valido", JOptionPane.INFORMATION_MESSAGE);
        JDialog jd = jop.createDialog("ERROR");
        jd.setLocation((int) this.getLocation().getX() + 300, (int) this.getLocation().getY() + 100);
        jd.setVisible(rootPaneCheckingEnabled);

    }

    private void panelComa() {
        JOptionPane jop = new JOptionPane("Dato con coma", JOptionPane.ERROR_MESSAGE);
        JDialog jd = jop.createDialog("ERROR");
        jd.setLocation((int) this.getLocation().getX() + 300, (int) this.getLocation().getY() + 100);
        jd.setVisible(rootPaneCheckingEnabled);

    }

    private void panelLetra() {
        JOptionPane jop = new JOptionPane("Dato no numerico", JOptionPane.ERROR_MESSAGE);
        JDialog jd = jop.createDialog("ERROR");
        jd.setLocation((int) this.getLocation().getX() + 300, (int) this.getLocation().getY() + 100);
        jd.setVisible(rootPaneCheckingEnabled);
    }

    private void jTextField_ValorCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ValorCelciusActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextField_ValorCelciusActionPerformed

    private void jTextField_ValorCelciusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ValorCelciusKeyPressed
        // TODO add your handling code here:

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            ejecutar();
        }

        if (key == KeyEvent.VK_ESCAPE) {
            System.exit(0);
        }

    }//GEN-LAST:event_jTextField_ValorCelciusKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_convertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2_Celsius;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_Respuesta;
    private javax.swing.JTextField jTextField_ValorCelcius;
    // End of variables declaration//GEN-END:variables
}
