/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package di_tarea_3_1_jpanelusuario;

import java.io.File;
import javax.swing.JLabel;

/**
 *
 * @author damt207
 */
public class JPanelUsuario extends javax.swing.JPanel {

    private File rutaImagen;

    public void setRutaImagen(File rutaImagen) {
        this.rutaImagen = rutaImagen;
        jPanelUsuarioImagen1.setRutaImagen(rutaImagen);
    }
    
    /**
     * Creates new form JPanelUsuario
     */
    public JPanelUsuario() {
        initComponents();
    }

    public JLabel getjLabelDateLogin() {
        return jLabelDateLogin;
    }

    public JLabel getjLabelUserName() {
        return jLabelUserName;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUserName = new javax.swing.JLabel();
        jLabelDateLogin = new javax.swing.JLabel();
        jPanelUsuarioImagen1 = new di_tarea_3_1_jpanelusuario.JPanelUsuarioImagen();

        setOpaque(false);

        jLabelUserName.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(197, 195, 192));
        jLabelUserName.setText("UserName");

        jLabelDateLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelDateLogin.setForeground(new java.awt.Color(197, 195, 192));
        jLabelDateLogin.setText("DateLogin");

        javax.swing.GroupLayout jPanelUsuarioImagen1Layout = new javax.swing.GroupLayout(jPanelUsuarioImagen1);
        jPanelUsuarioImagen1.setLayout(jPanelUsuarioImagen1Layout);
        jPanelUsuarioImagen1Layout.setHorizontalGroup(
            jPanelUsuarioImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelUsuarioImagen1Layout.setVerticalGroup(
            jPanelUsuarioImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanelUsuarioImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUserName)
                    .addComponent(jLabelDateLogin))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabelDateLogin)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanelUsuarioImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDateLogin;
    private javax.swing.JLabel jLabelUserName;
    private di_tarea_3_1_jpanelusuario.JPanelUsuarioImagen jPanelUsuarioImagen1;
    // End of variables declaration//GEN-END:variables
}
