/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import main.Main;

/**
 *
 * @author damt207
 */
public class Welcome extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Welcome() {
        initComponents();
        
        jLabelWelcome.setText("Hola " + Main.usuarioLogin.getName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(940, 690));
        setMinimumSize(new java.awt.Dimension(940, 690));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(940, 690));

        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(197, 195, 192));
        jLabelWelcome.setText("Hola");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelWelcome;
    // End of variables declaration//GEN-END:variables
}
